import type { WorkflowState } from "./types";

/** Default resume-tailoring workflow: 9 nodes in sequence. */
export const SAMPLE_WORKFLOW: WorkflowState = {
  nodes: [
    {
      id: "initialInput",
      type: "initialInput",
      label: "Initial Input",
      position: { x: 40, y: 200 },
      description: "Job title, company, JD, options",
      data: {
        jobTitle: "",
        companyName: "",
        jobDescription: "",
        jobLink: "",
        sheetRowIndex: "",
        templateId: "modern",
        options: { maxPages: 2, tone: "professional", atsMode: true, preserveJobOrder: true },
      },
    },
    {
      id: "resumeSelection",
      type: "resumeSelection",
      label: "Resume Selection",
      position: { x: 260, y: 200 },
      description: "Choose a sheet row (resume_url on Drive)",
      data: {},
    },
    {
      id: "jdParsing",
      type: "jdParsing",
      label: "JD Parsing",
      position: { x: 480, y: 200 },
      description: "Parse and normalize job description",
      data: {},
    },
    {
      id: "tailorAi",
      type: "tailorAi",
      label: "Tailor AI",
      position: { x: 700, y: 200 },
      description: "Tailor resume to JD",
      data: { model: "gpt-4o-mini" },
    },
    {
      id: "resumeValidation",
      type: "resumeValidation",
      label: "Resume Validation",
      position: { x: 920, y: 200 },
      description: "Validate tailored resume",
      data: {},
    },
    {
      id: "templateSelection",
      type: "templateSelection",
      label: "Template Selection",
      position: { x: 1140, y: 80 },
      description: "Choose PDF template",
      data: { templateId: "modern" },
    },
    {
      id: "resumeToTemplateMapping",
      type: "resumeToTemplateMapping",
      label: "Resume-to-Template Mapping",
      position: { x: 1360, y: 200 },
      description: "Map data to template",
      data: {},
    },
    {
      id: "pdfBuild",
      type: "pdfBuild",
      label: "PDF Build",
      position: { x: 1580, y: 200 },
      description: "Generate PDF",
      data: {},
    },
    {
      id: "download",
      type: "download",
      label: "Download",
      position: { x: 1800, y: 200 },
      description: "PDF, JSON, ATS results",
      data: {},
    },
  ],
  edges: [
    { id: "e1", sourceId: "initialInput", targetId: "resumeSelection" },
    { id: "e2", sourceId: "resumeSelection", targetId: "jdParsing" },
    { id: "e3", sourceId: "jdParsing", targetId: "tailorAi" },
    { id: "e4", sourceId: "tailorAi", targetId: "resumeValidation" },
    { id: "e5", sourceId: "resumeValidation", targetId: "templateSelection" },
    { id: "e6", sourceId: "templateSelection", targetId: "resumeToTemplateMapping" },
    { id: "e7", sourceId: "resumeToTemplateMapping", targetId: "pdfBuild" },
    { id: "e8", sourceId: "pdfBuild", targetId: "download" },
  ],
};
